Border Radius Previewer
Ibnballo1/border-radius-previewer pull request #1
Opened 2023-01-10 14:31 UTC by Ibnballo1

In this PR, I created a web app where someone can preview the border radius of the box in the app.
I completed this project by implementing the following:

- Created a box to show the preview
- Have an input field where the user can enter the value of the border-radius
- The values entered will be affected as follows:
    - if one value (with its unit) is entered, it will affect the four corners
    - if two values are entered, the first value will affect the border-top-left and border-bottom-right radius while the second value will affect the border-top-right and border-bottom-left radius.
    - if three values are entered, then the first value is for the top-left border, while the second value is for the top-right and bottom-left border, and the third value is for the bottom-right border.
    - if four values are entered, then each value represents each border-radius from top-left to bottom-left.

2023-01-10 14:44 UTC, shasherazi commented
I can't test your website because the JavaScript script path could not be found. Please use relative paths here
https://github.com/Ibnballo1/border-radius-previewer/blob/0d4e11e74b4ef11faa16793b15e2d6789aabb89d/index.html#L33

Use `./app.js` instead of `/app.js`. See [this StackOverFlow question](https://stackoverflow.com/questions/37176191/my-html-file-wont-link-with-my-javascript-file) for more info.

2023-01-10 14:58 UTC, Ibnballo1 commented
> I can't test your website because the JavaScript script path could not be found. Please use relative paths here
> 
> https://github.com/Ibnballo1/border-radius-previewer/blob/0d4e11e74b4ef11faa16793b15e2d6789aabb89d/index.html#L33
> 
> Use `./app.js` instead of `/app.js`. See [this StackOverFlow question](https://stackoverflow.com/questions/37176191/my-html-file-wont-link-with-my-javascript-file) for more info.

Use the dev branch @shasherazi , thanks

2023-01-10 15:00 UTC, shasherazi commented
> Use the dev branch @shasherazi , thanks

I'm using dev branch, there's no js file in main branch. The site doesn't work for me on netlify either.

2023-01-10 15:00 UTC, Ibnballo1 commented
> I can't test your website because the JavaScript script path could not be found. Please use relative paths here
> 
> https://github.com/Ibnballo1/border-radius-previewer/blob/0d4e11e74b4ef11faa16793b15e2d6789aabb89d/index.html#L33
> 
> Use `./app.js` instead of `/app.js`. See [this StackOverFlow question](https://stackoverflow.com/questions/37176191/my-html-file-wont-link-with-my-javascript-file) for more info.

I have done that, check again, please

2023-01-10 15:14 UTC, Ibnballo1 commented on app.js
> +// console.log(`all radius value is ${allRadius.value}`);
It will be nice if you remove unused code as this will make your code neat

2023-01-10 15:14 UTC, Ibnballo1 commented on app.js
> +  // console.log(split);
Please, remove commented code to make your code look neat

2023-01-10 15:28 UTC, shasherazi requested changes
Please remove all the comments, as they make the code hard to read.

2023-01-10 15:28 UTC, shasherazi commented on app.js
> +const allInput = document.querySelectorAll(".input");
Where is this being used? Please remove it if it isn't being used anywhere.

2023-01-10 15:28 UTC, shasherazi commented on app.js
> +let split = '';
I think these variables should be defined in the event listener because they are only used there.

2023-01-10 15:31 UTC, shasherazi commented on app.js
> +  alert("Border Radius: " + allRadius.value);
I think it would be better if you use a custom modal for the notification that says something like `Copied!` instead of using `alert()`. 

`alert()` stops the user from doing anything else, it can't be styled with CSS, and different browsers implement it differently. That's why it shouldn't be used.

2023-01-10 15:35 UTC, Ibnballo1 reviewed
You have really worked hard to complete this project. You still have to do somethings... You are almost there

2023-01-12 06:50 UTC, shasherazi commented on app.js
> +  const tests = /[a-zA-Z]/.test(borderRadiusValue);
I think it would be better if you explicitly check for possible CSS units such as `em`, `rem`, `%` etc.

2023-01-12 09:42 UTC, Ibnballo1 commented on app.js
> +  const tests = /[a-zA-Z]/.test(borderRadiusValue);
Thanks @shasherazi , I will do this later but please kindly help approve it

2023-01-12 09:57 UTC, shasherazi approved these changes
Ok but be sure to add this in next pull request please.

2023-01-12 14:41 UTC, merged